---

# Main tasks file for grafana role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::grafana'
    - 'role::grafana::init'
