---

# Main tasks file for grafana role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::grafana'
    - 'role::grafana::init'
    - 'role::grafana::install'


- name: 'INSTALL | Manage os family installation tasks'
  include: "{{ role_path }}/tasks/install/{{ ansible_os_family | lower }}_family.yml"
  tags:
    - 'role::grafana'
    - 'role::grafana::install'
