---

# Main tasks file for grafana role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::grafana'
    - 'role::grafana::config'
    - 'role::grafana::init'
    - 'role::grafana::install'


- name: 'INSTALL | Manage os family installation tasks'
  include: "{{ role_path }}/tasks/install/{{ ansible_os_family | lower }}_family.yml"
  become: True
  tags:
    - 'role::grafana'
    - 'role::grafana::install'


- name: 'CONFIG | Manage configuration files'
  include: "{{ role_path }}/tasks/configure.yml"
  become: True
  tags:
    - 'role::grafana'
    - 'role::grafana::config'


- name: 'CONFIG | Manage service state'
  include: "{{ role_path }}/tasks/manage_service.yml"
  become: True
  tags:
    - 'role::grafana'
    - 'role::grafana::config'


- name: 'CONFIG | Manage datasources configuration tasks'
  include: "{{ role_path }}/tasks/manage_datasources.yml"
  become: True
  tags:
    - 'role::grafana'
    - 'role::grafana::config'
